### ISSUE TITLE
List app for Android

### ISSUE THREAD

**Issue by PanderMusubi** [superjohan/ifm#15]
If possible, list this app for listening to Intergalactic FM on Android in the iTunes shop listing.

http://www.y20k.org/transistor/

We are working that this app supports the streams, metadata and artwork of IFM.

**Comment by superjohan** [comment]
I'm not sure Apple would like that. They've usually frowned upon even mentioning Android in store listings or release notes.

**Comment by PanderMusubi** [comment]
Aw, too bad but understand that you don't want your app banned because of it.
